### ISSUE TITLE
Feature Request: Add Objective-C parser

### ISSUE THREAD

**Issue by bhamiltoncx** [lezer-parser/lezer#12]
Looks like the C++ parser doesn't handle Objective-C. It'd be nice to add an Objective-C parser (stretch goal: Objective-C++ parser. :)

**Comment by marijnh** [comment]
I'm not taking feature requests—the idea behind distributing the parsers as separate packages is that other people can build and maintain them, so that the entire maintenance burden doesn't fall on me. So your options are to hope someone builds such a parser at some point, or to build it yourself.
