### ISSUE TITLE
Fix for bug in heap insert code

### ISSUE THREAD

**Issue by afri** [lezer-parser/lezer#13]
There's an indexing bug in the heap insert code which causes all sorts of parsing weirdness.
At https://github.com/lezer-parser/lezer/blob/master/src/parse.ts#L273, the code
```
let parentIndex = index >> 1, parent = this.stacks[parentIndex]
```
should be
```
let parentIndex = (index-1) >> 1, parent = this.stacks[parentIndex]
```

**Comment by marijnh** [comment]
Fixed in attached patch.
