### ISSUE TITLE
Explore potential reductions after skipping tokens

### ISSUE THREAD

**Issue by afri** [lezer-parser/lezer#14]
For the code
```
`
foo(x);
```
the JS parser produces:
```
Script(ExpressionStatement(TemplateString(⚠)))
```
Tree-sitter finds the superior parsing:
```
program [0, 0] - [2, 0])
  ERROR [0, 0] - [0, 1])
  expression_statement [1, 0] - [1, 7])
    call_expression [1, 0] - [1, 6])
      function: identifier [1, 0] - [1, 3])
      arguments: arguments [1, 3] - [1, 6])
        identifier [1, 4] - [1, 5])
```
I believe this is because lezer (currently) doesn't try to skip any tokens in `forceReduce`?

**Comment by marijnh** [comment]
It'll skip tokens with `recoverByDelete`, and then the next time that stack is advanced try a forced reduction again (unless that stack got pruned somehow, which is currently not terribly predictable). Though in this case, since the initial token can be consumed successfully, you'd actually need just a forced reduction in Lezer, to get out of the template string, and token deletion doesn't seem to come into it.

The first test case [in this file](https://github.com/lezer-parser/lezer-generator/blob/master/test/cases/Recover.txt#L13) covers something similar (where it does work).

We absolutely need to find a better way to express stack pruning, to make it easier to reason about things like this.

**Comment by afri** [comment]
Hmm, I think I don't understand conceptually how error recovery in the TemplateString case is supposed to work in lezer (and how it does seem to work in tree-sitter).

After encountering the first backtick, the external TemplateString tokenizer kicks in and shifts one opaque 'foo(x);' token. By the time error recovery is done (at EOF), wouldn't 'foo(x)' need to be retokenized somehow to parse `foo(x);` into an CallExpression?

**Comment by marijnh** [comment]
Ah, I see what you mean, Lezer will just treat the entire input as a template string. Yeah, in cases like this, where the rest of the input is valid until the missing closing tick, error recovery just won't kick in until the end of the file. Parsing is a single-pass process, the parser will never backtrack over already accepted tokens.

I think tree-sitter tokenizes the entire template string as a single token, and thus will notice that it's invalid right away. This has the disadvantage of not being very incremental for huge template strings (see also https://github.com/tree-sitter/tree-sitter/issues/300).

The Lezer JS grammar could be written like that, but at the moment it intentionally splits template strings into smaller elements to preserve incrementality. I don't think this case is worth changing that (the "unfinished template string" interpretation isn't inherently less reasonable than "stray backtick with code after it"). If you'd write the tree-sitter grammar for template strings along the lines of the Lezer grammar, it'd show the same behavior.

**Comment by afri** [comment]
The reason why this particular case is so annoying is that, if you edit code and insert a template string towards the beginning of your file, it temporarily messes up **all** syntax highlighting of the remainder of the file. 

This will happen for all languages that have multi-line string or comment constructs. (Interestingly it doesn't currently happen in the JS parser for an opening `/*` - which is erroneously being parsed as the start of a valid regexp)

I'm still not sure how tree-sitter manages this case. It produces a 'good' parse, even if there is some TemplateString-specific sub-structure. E.g.
```
` foo
${x}

foo(x);
```
is being parsed into
```
program [0, 0] - [4, 0])
  ERROR [0, 0] - [1, 4])
    template_substitution [1, 0] - [1, 4])
      identifier [1, 2] - [1, 3])
  expression_statement [3, 0] - [3, 7])
    call_expression [3, 0] - [3, 6])
      function: identifier [3, 0] - [3, 3])
      arguments: arguments [3, 3] - [3, 6])
        identifier [3, 4] - [3, 5])
```

**Comment by marijnh** [comment]
> I'm still not sure how tree-sitter manages this case

It refuses to tokenize a template string open token if it can't find a closing `` ` `` character, so it never treats the stray backtick as opening a template string. However, if your code below the lone backtick has another template string, it _does_ create a template string token and its output is no better than what Lezer currently produces.

**Comment by afri** [comment]
But if it was as simple as looking ahead for a closing backtick, then I wouldn't expect tree-sitter to parse `${x}` into a `template_substitution` in the code above. But it does, **and** it still parses `foo(x)` as a `call_expression`.

**Comment by marijnh** [comment]
Right, a `${` can obviously also finish a template string token.
