### ISSUE TITLE
Inline terms not exported

### ISSUE THREAD

**Issue by ashtonsix** [lezer-parser/lezer#16]
It is my expectation that this grammar:

```grammar
@top Program { Term[@export] { "." } }
```

Would produce a terms file like this (or throw an error):

```js
export const
  Program = 1,
  Term = 2
```

But it actually produces a terms file like this:

```js
export const
  Program = 1
```

For comparison, here is a grammar that produces the expected terms file:

```grammar
@top Program { Term }
Term[@export] { "." }
```

**Comment by marijnh** [comment]
This is by design, because you can have multiple inline rules with the same name. Move them to the top level to export them.

**Comment by marijnh** [comment]
Attached patch adds a warning when you do this.
