### ISSUE TITLE
Incremental parses aren't fast enough

### ISSUE THREAD

**Issue by marijnh** [lezer-parser/lezer#16]
Parsing a 400kb JS file takes about 180ms. Making a change somewhere in the middle and re-parsing takes about 30ms.

Interestingly, increasing the size of the total document doesn't change the incremental re-parse time much. Which is the intention. For tiny documents re-parsing is also cheap, since there even re-parsing the entire thing doesn't take much time.

But once the document has a significant size there seems to be a 30ms minimum.

**Comment by marijnh** [comment]
Lowering the default buffer length _does_ seem to have a significant impact. Moving from 1024 to 128 cuts the re-parse time by 90%, into a much more comfortable 3ms. This makes sense, on some level, since an incremental parse will have to re-parse at least the buffer around the change. But the normal cost of parsing 1024 elements isn't even close to 30ms (more in the range of 0.4ms).

Decimating buffer size like that seems to blow up memory use by about a factor 3.3, so that's a definite disadvantage.

Next up is, I guess, investigating why the cost is so much more than expected, by counting reallocated buffers and reused nodes, etc.

**Comment by marijnh** [comment]
The issue appears to be related to the tree-balancing code getting confused by comment (skipped) nodes, leading to a wildly unbalanced tree, plus the fact that buffers, once lifted from their parent tree, are never reused. So the wonky tree shape causes a lot of buffers to be dumped out of their parent when upacking the tree for the change, and then those all need to be re-parsed. (Which amounts to about 25% of the file in my test case.)

**Comment by marijnh** [comment]
I've pushed a bunch of patches to all three main repositories that address this. Unfortunately, the changes are breaking, so I'll have to release a 0.7.0 soon. Fortunately, they make parsing in general a bit faster (as well as greatly improving incremental parsing performance).

I still see the occasional performance cliff (back to 40ms to 70ms for an incremental parse, which at this point is half the initial parse time) when putting the change in random positions. Those are probably changes that change the meaning of the subsequent code in such a way that a large chunk has to be re-parsed. That remains a thing that can happen, and I guess that's just something we'll have to deal with through early aborts and such.

**Comment by marijnh** [comment]
0.7.0 is out, which should do a lot better here.

**Comment by nikku** [comment]
Great work :clap:. This release also seems to generate more compact parsers (at least observable in my grammar).
