### ISSUE TITLE
Include repository field in package.json

### ISSUE THREAD

**Issue by curran** [lezer-parser/lezer#18]
Minor issue, but just wanted to provide some feedback that when viewing the `lezer` package page on NPM...

![image](https://user-images.githubusercontent.com/68416/73238526-5a6eef00-41bf-11ea-9ead-88975866886d.png)

The link back to the GitHub repository is missing. This threw me off and I bet others would also feel the same.

**Comment by marijnh** [comment]
Good point, guess I generated these before setting up the github stuff. Attached patches also adds the field to the other repositories.
