### ISSUE TITLE
The NPM package contains many superfluous files

### ISSUE THREAD

**Issue by chocolateboy** [lezer-parser/lezer#23]
The size of the NPM [tarball](https://registry.npmjs.org/lezer/-/lezer-0.8.4.tgz) is 548 KB and its unpacked size is 3.5 MB. The same applies to the lezer-generator package, whose 1.3 MB [tarball](https://registry.npmjs.org/lezer-generator/-/lezer-generator-0.8.4.tgz) is 9.2 MB unpacked!

Both packages include cache directories for [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2) (3 MB and 8 MB respectively), TypeScript source code, tests, test fixtures etc.

I would suggest using the [`files` array](https://docs.npmjs.com/files/package.json#files) in your `package.json`s to only include the files you intend to publish.

**Comment by marijnh** [comment]
Oh, ew, good point. I've published a 0.8.5 of lezer and lezer-generator which should help with this.
