### ISSUE TITLE
Provide more context when spec files cannot be parsed using built-in tester

### ISSUE THREAD

**Issue by nikku** [lezer-parser/lezer#25]
The built-in tester fails on simple things such as missing newline at the end of the test file and gives me no actual information about it.

The following works:

```
# Expression

a

==>

Other(Name(a))

```

The following fails with `Error: Unexpected file format in {test_file}`

```
# Expression

a

==>

Other(Name(a))
```

#### Proposal

* Handle missing newline on end of file gracefully _or_ improve error messages.

Happy to contribute an improvement, if we can settle down on one of the options.

**Comment by marijnh** [comment]
The test runner is not a very well-throught-out piece of software. Attached patch fixes the trailing-newline issue, and feel free to open further issues when you run into blatant misbehavior, but for now I don't plan to put a lot of further work into its usability.
