### ISSUE TITLE
Help contributing?

### ISSUE THREAD

**Issue by drwpow** [lezer-parser/lezer#28]
👋 Hello! I came across this project today and wanted to contribute, but wasn’t sure how.

I noticed these projects could probably use more testing and an improved CI setup (I’m partial to GitHub Actions, which is free for public projects like this).

There’s also the option to (re)combine all the different repos into one, with helps with testing & CI (you can still manage independent versions & changelogs for each package, but you don’t have to reinvent the wheel managing tests for dozens of repos). One repo also helps with GitHub stars (which isn’t really important, but also, it’s not _not_ important) 🙂.

Would either be helpful to this project? Happy to help if so.

**Comment by marijnh** [comment]
No thank you—neither of those are desired at the moment, and if they were, I'd prefer to do that kind of thing myself in any case.

**Comment by drwpow** [comment]
Thanks for replying. Are there other types of contributions that are welcome? I usually just offer testing/CI as it doesn’t affect the core project, but happy to contribute in whatever capacity is needed.

**Comment by marijnh** [comment]
Most kinds of contributions are going to require a rather deep understanding of the system. At the moment there's no real need to add more tests.
