### ISSUE TITLE
A misused term in the documentation

### ISSUE THREAD

**Issue by arucil** [lezer-parser/lezer#29]
In the documentation of `InputStream`, the term *UTF-16 code point* is used, which is incorrect. There is actually no such thing as *UTF-16 code point*, I think what the author means is [*UTF-16 code unit*](https://unicode.org/glossary/#code_unit).

A *UTF-16 code unit* is either a single [*Unicode scalar value*](https://unicode.org/glossary/#unicode_scalar_value), or part of a [*UTF-16 surrogate pair*](https://unicode.org/glossary/#surrogate_pair).

**Comment by marijnh** [comment]
Good point. Attached patch switches that over to 'code unit'.
