### ISSUE TITLE
Potentially missing grammar for javascript tokenizer (Symbol.iterator)

### ISSUE THREAD

**Issue by kdog3682** [lezer-parser/lezer#31]
class Foo {
        constructor() { /* works fine */ }
        method() { /* works fine */ }
        [Symbol.iterator]() { /* doesnt seem to work */ }
    }

Maybe it is an error on my part, but when I am trying to tokenize the above code, it breaks down around the Symbol.iterator part.

**Comment by marijnh** [comment]
Attached patch should fix this.
