### ISSUE TITLE
Consider to allow number in SyntaxNode.getChild / SyntaxNode.getChildren

### ISSUE THREAD

**Issue by Nexucis** [lezer-parser/lezer#37]
the method `getChild()` and `getChildren()` doesn't allow to retrieve the child with the number ID but only by using the name of the node.

So when you are using the ID exported by lezer, then you cannot use it in this method.

Would you consider to change the prototype of the methods by ? :

```typescript
getChild(type: string | number, before?: string | number | null, after?: string| number | null): SyntaxNode | null;
getChildren(type: string | number, before?: string | number | null, after?: string | number | null): SyntaxNode[];
```

**Comment by marijnh** [comment]
That'd be reasonable, I guess. We could also have `NodeType.is` follow this change. The implementation could check the group property check entirely when the argument is a number. Want to submit a pull request?

**Comment by Nexucis** [comment]
yeah ok why not.

I will look at the method `NodeType.is`. Not sure I follow everything you said, it should be clearer once I will have the code in front of me

**Comment by Nexucis** [comment]
So I was looking at the code, applying the changes and I ended up here: https://github.com/lezer-parser/lezer-tree/blob/master/src/tree.ts#L90

So I understood how it is supposed to be used (i.e. https://github.com/lezer-parser/lezer/blob/master/src/parse.ts#L649). And I supposed I just have to modify the `deserialize` function in order to retrieve the number of the node instead of the name, I just didn't get how the struct is defined. 

Do you have a documentation/comment/code that would explain a bit how the data are structured ?

**Comment by marijnh** [comment]
No, you don't have to change how the group prop works—just make queries for numbers ignore it.
