### ISSUE TITLE
Expose top Level statement as a number

### ISSUE THREAD

**Issue by Nexucis** [lezer-parser/lezer#38]
With Lezer v0.12.0, we had to name the top level statement. But the associated constant is not in the file `parser.terms.js`.

Would you consider to put it ?

**Comment by marijnh** [comment]
Yes, that should definitely be there. I'll take a look why it isn't later.

**Comment by Nexucis** [comment]
By the way, regarding the top level statement it's today possible to call the top level statement with the same name as another statement.

For example: 

```
@top Expr {
  AggregateExpr |
  BinaryExpr |
  FunctionCall |
  MatrixSelector |
  NumberLiteral |
  OffsetExpr |
  ParenExpr |
  StringLiteral |
  SubqueryExpr |
  UnaryExpr |
  VectorSelector
}

Expr {
  AggregateExpr |
  BinaryExpr |
  FunctionCall |
  MatrixSelector |
  NumberLiteral |
  OffsetExpr |
  ParenExpr |
  StringLiteral |
  SubqueryExpr |
  UnaryExpr |
  VectorSelector
}
```

This is allowed today. Don't know if it's normal or not. But from my side, it was a sort of explanation why the top level statement wasn't exposed in the file `parser.term.js`. Because in the above case, well you won't be able to have the same constant twice.

**Comment by marijnh** [comment]
That's not intentional either. I've fixed the first issue in https://github.com/lezer-parser/lezer-generator/commit/39635a6ce29187a644b2648f86edc0acf3e5bc5a , and the second in https://github.com/lezer-parser/lezer-generator/commit/b3837a2b32151748a349856f8e4bf3b2c0f9b5fc

**Comment by Nexucis** [comment]
ah ok. Thanks !

**Comment by Nexucis** [comment]
Also, today it's not possible to use the top-level statement in the other statement.

For example: 
```
@top Expr {
  AggregateExpr |
  BinaryExpr |
  FunctionCall |
  MatrixSelector |
  NumberLiteral |
  OffsetExpr |
  ParenExpr |
  StringLiteral |
  SubqueryExpr |
  UnaryExpr |
  VectorSelector
}

BinaryExpr {
  Expr !pow Pow        BinModifier Expr |
}
```
is not allowed. Is it intentional ? 

From my point of view, it would be great to be able to use the top-level statement in the grammar. Like that it reduces a bit the number node.
And also it will simplify a bit the iteration other the tree. I mean with the current implementation, when you want to iterate other the tree, if you want to access to the useful node (in the above example, it's `BinaryExpr`), then you have to go first to the first child directly. So the top level node doesn't have a super utility.

**Comment by marijnh** [comment]
> Is it intentional ?

Yes, that's intentional. The system is currently using the test 'is this state the end of a top rule' to distinguish accepting states at the end of the input, and that wouldn't work anymore if these rules were usable from other positions.

**Comment by marijnh** [comment]
(Which isn't to say that couldn't be changed, it's just that I don't consider it a priority, since it's usually preferable to have a specific top node type anyway—CodeMirror 6 uses those to determine language boundaries in mixed language documents, for example.)

**Comment by Nexucis** [comment]
ok understood :) thanks for the detailed explanation !
