### ISSUE TITLE
Lezer crashes when parsing python code in codemirror 6

### ISSUE THREAD

**Issue by Yaakov-Belch** [lezer-parser/lezer#40]
A specific input text crashes codemirror 6 in python mode: Chrome displays a unhelpful "Aw snap" page.  Firefox asks whether to stop the script -- and shows an stack trace pointing at the function `work` in the `lezer` module:

> Script terminated by timeout at: parse.ts:302:18
ParseContext.prototype.advance@http://localhost:3001/@modules/lezer/dist/index.es.js:914:25
work@http://localhost:3001/@modules/@codemirror/next/syntax/dist/index.js:295:26
advance@http://localhost:3001/@modules/@codemirror/next/syntax/dist/index.js:331:24
...

**To reproduce the bug:** Paste the content of the attached file `cm6bug.txt` into a codemirror 6 instance configured with `basicSetup`, `python()` and with an `indentUnit` of four spaces.  Then, in line 11, put the cursor before the `#` sign and press `space` a few times.

I attached also a **bug-demo web app** in `cm6bug.zip` with this setting.  Run it with `npm install; npm run dev`.  The python code will already be in the editor.  Go to line 11 and insert a few spaces before the `#` sign to trigger the bug.

[cm6bug.txt](https://github.com/lezer-parser/lezer/files/5561927/cm6bug.txt)

[cm6bug.zip](https://github.com/lezer-parser/lezer/files/5561923/cm6bug.zip)

**Comment by marijnh** [comment]
Thanks for the reproduction. Patch d6b16351fd9b, released as lezer 0.12.1, should fix it.

**Comment by Yaakov-Belch** [comment]
Indeed, this fix resolves the problem.
Thank you very much!
