### ISSUE TITLE
[generator] dist/rollup-plugin-lezer.cjs is missing in v1.4.1

### ISSUE THREAD

**Issue by hubgit** [lezer-parser/lezer#40]
We're experiencing an issue with the latest version of `@lezer/generator` (1.4.1, published earlier today), as the file `dist/rollup-plugin-lezer.cjs` is no longer present in the published package.

**Comment by hubgit** [comment]
The import `@lezer/generator/rollup` is mapped to `./dist/rollup-plugin-lezer.cjs`:

https://github.com/lezer-parser/generator/blob/445a6d8641b1fea147c9d2274565d434dbacb66f/package.json#L20-L23

A [recent commit](https://github.com/lezer-parser/generator/commit/e5076e005372566f62013ead5b8886d558450c96#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45c) changed the build process, and `rollup-plugin-lezer.cjs` (which was previously listed as an output in `rollup.config.js`) is not included in the new `build.js`:

https://github.com/lezer-parser/generator/commit/e5076e005372566f62013ead5b8886d558450c96#diff-7d111b05fe05c50beb729d1e99a36010fbda8c89b57a1a26ac3e7b0778a0ed53R12-R13

This is a breaking issue for `@codemirror/buildhelper`, which currently installs v1.4.1 of `@lezer/generator` on a fresh install.

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch should help.
