### ISSUE TITLE
Generated `specialized` field is not compatible with typescript strict mode

### ISSUE THREAD

**Issue by berekuk** [lezer-parser/lezer#41]
From https://github.com/lezer-parser/lezer/issues/11#issuecomment-907630556:

> I believe there is currently nothing in the generated output that would require a type declaration, so you should be able to just treat it as typescript.

This seems to have changed at some point.

My generated parser includes this code:

```
  specialized: [{term: 102, get: value => spec_identifier[value] || -1}],
```

Which is not compatible with Typescript strict mode or `"noImplicitAny": true`:
<img width="449" alt="Captura de pantalla 2023-08-17 a la(s) 12 43 12" src="https://github.com/lezer-parser/lezer/assets/89368/4298fdc9-d95f-4096-ba46-cceb1b690b8e">

**Comment by marijnh** [comment]
Does attached patch look like it would work for you?

**Comment by berekuk** [comment]
I think in my case the code was generated by a different branch that you need to update too, line 493 after your patch. (I see `|| -1` on the screenshot, not `<< 1`).

**Comment by marijnh** [comment]
Oh, good point. Added another patch that makes the change there as well.

**Comment by berekuk** [comment]
Looks good now!
