### ISSUE TITLE
Cannot test for multiple groups in grammar using built-in tester

### ISSUE THREAD

**Issue by nikku** [lezer-parser/lezer#43]
I'm using the test utilities shipped with `lezer-generator` to test my grammar, however I cannot test for multiple groups being present.

#### Example grammar

```
@top T {
  expression+
}

expression[@isGroup=Expression] {
  literal
}

literal[@isGroup=Literal] {
  BooleanLiteral
}

BooleanLiteral {
  "true" | "false"
}
```

Given that grammar, `BooleanLiteral` should have both, `Expression` and `Literal` groups attached, intuitively in some kind of nested array syntax, i.e. the following.

```
# Assign Node Groups

true

==> T(BooleanLiteral[group=[Expression,Literal]])
```

Does there exist a way to test for multiple groups yet.

#### Expected

I can test for multiple group values.

-----

Related, but nice to have: I believe the existing error message if a node does not match regarding the props could be improved:

```
Error: Expected BooleanLiteral in T, got BooleanLiteral at 0
```

The error is opaque regarding the fact that a particular prop does not match.

**Comment by marijnh** [comment]
You can use a space-separated list of group names (as in `[group="Expression Literal"]`), but unfortunately that means you have to encode the precise order in which the generator assigns the groups, which isn't really specified.

Agreed that the error message is abysmal in this case. Want to submit a PR to fix that? (Maybe by making `match` return an optional error string.)

**Comment by nikku** [comment]
> You can use a space-separated list of group names (as in `[group="Expression Literal"]`)

Thanks. The space separation is a notation that did not occure to me at all, even after reading the source code :wink:.

> [...] unfortunately that means you have to encode the precise order in which the generator assigns the groups, which isn't really specified.

The list of group names is being populated in order of nesting (group assignment) as it looks like? At least that is what I see in my tests. That is absolutely what I'd expect, so no need to change anything here.

I'll see if I can follow up on a PR to improve the error output. 

Closing this issue. Thanks again for pointing me into the right direction.
