### ISSUE TITLE
Add a printer package

### ISSUE THREAD

**Issue by deemp** [lezer-parser/lezer#45]
Recently, I started making a new parser and discovered there's still no official parse tree pretty printer. I found one on the CodeMirror forum ([link](https://discuss.codemirror.net/t/whats-the-best-to-test-and-debug-grammars/2542)) and saw the original post has gotten 1.8K views since 2020.

Currently, I packaged that pretty printer ([link](https://github.com/deemp/printer)) to use for my new package. However, it'd be nice to have an official package, with at least some parse tree pretty-printing format (not necessarily JSON).

@marijnh, could you please consider adding such a printer to the `@lezer` family?

**Comment by marijnh** [comment]
No. That's not something I'm going to work on.

**Comment by deemp** [comment]
May I call it `@lezer/printer` to make it searchable by prefix on npmjs? Or `@lezer-unofficial/printer`? Or how?

**Comment by marijnh** [comment]
I don't really want to open the `@lezer` namespace to 3rd-party code. Just `lezer-printer` or `@lezer-unofficial/printer` is perfectly fine.

(You are aware of the very basic pretty-printing that `Tree.toString` provides, no?)

**Comment by deemp** [comment]
Okay, it's [@lezer-unofficial/printer](https://www.npmjs.com/package/@lezer-unofficial/printer). I added a comparison with `Tree.toString` to the README.
