### ISSUE TITLE
tree.children is undefined in @lezer/common

### ISSUE THREAD

**Issue by gtm-nayan** [lezer-parser/lezer#46]
When upgrading from v1.0.3 to v1.1.0, I ran into this error coming from the @lezer/common package:

```
CodeMirror plugin crashed: TypeError: tree.children is undefined
    hasChild index.js:1244
    nextChild index.js:724
    enterChild index.js:1008
    firstChild index.js:1020
    highlightRange index.js:364
    highlightRange index.js:372
    highlightRange index.js:372
    highlightTree index.js:295
    buildDeco index.js:1741
    update index.js:1733
    update index.js:1986
    updatePlugins index.js:6821
    update index.js:6727
    _dispatch index.js:6585
    dispatch index.js:6653
```

**Comment by marijnh** [comment]
You probably have multiple different versions of @lezer/common in your tree, breaking `instanceof` checks. Remove your package lock and reinstall your dependencies.

**Comment by gtm-nayan** [comment]
Ahh, thanks.

**Comment by marijnh** [comment]
Could you tell me which npm version you are using?

**Comment by gtm-nayan** [comment]
It was pnpm in my case, v8.7.1.

**Comment by marijnh** [comment]
I *think* upgrading to npm 9.x should make it properly deduplicate when upgrading packages (but I'm not sure that hold in all situations)
