### ISSUE TITLE
Extend bundler support to Webpack and Vite using Unplugin

### ISSUE THREAD

**Issue by illright** [lezer-parser/lezer#48]
There's a project called [Unplugin](https://github.com/unjs/unplugin) which acts as an adapter of a Rollup-like plugin API and creates plugins that are supported by most bundlers. Looking at the source code of the Rollup plugin for the generator, it seems like it should be a drop-in replacement, though I haven't tried it, and we'd get support for Webpack, Vite, and even esbuild (though not in watch mode, it seems). Is this something you would be open to?

I'm considering giving it a shot, would like to hear your take on it first.

**Comment by marijnh** [comment]
This sounds useful. The entry point would have to be a specific new file, I guess? I'd be interested in a PR.

**Comment by marijnh** [comment]
https://github.com/lezer-parser/yaml/issues/1

**Comment by fasiha** [comment]
@marijnh thanks for fixing this! Do we have to update our version of `lezer` to pick up this and the fix to https://github.com/lezer-parser/yaml/issues/1? (I asked there also, sorry for double-ping!)
