### ISSUE TITLE
clone() or fork() for TreeCursor

### ISSUE THREAD

**Issue by msteen** [lezer-parser/lezer#49]
I think an useful addition to the `TreeCursor` class would be a `clone()` or `fork()` method like in some of the other `Cursor` classes used internally. I was thinking of some potential solutions to a problem of mine and I was thinking to have the cursor move to a specific node and then have multiple handlers traverse from that point depending on their needs, but being able to start from the same exact node will be lost due to the mutability of the cursor, and using `moveTo()` might not reset it to the intended node (multiple nested nodes could start or end at the same position). Being able to clone/fork the cursor would solve that. Though I might have missed something in the API that makes it so that its not needed, but I could not find it myself.

**Comment by marijnh** [comment]
You should be able to do `.node.cursor` to get a new instance of a cursor pointing at the same place. Does that solve this for you?

**Comment by msteen** [comment]
Ah, I mostly ignored `SyntaxNode` so far over cursor, so missed it. It does solve it, thanks!
