### ISSUE TITLE
Syntax highlighting demo

### ISSUE THREAD

**Issue by curran** [lezer-parser/lezer#5]
This may be out of scope for the project, but would it be possible to put together a demo where code is syntax highlighted using Lezer? I'm thinking the output could be similar to that of [Prism](https://prismjs.com/), like this:

```html
<pre><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
```

The above example is from this demo http://satya164.xyz/react-simple-code-editor/ , which uses an interesting approach to create a code editor similar to CodeMirror (a syntax-highlighted `pre` tag aligned on top of a `textarea`). The main drawback of that approach seems to be that the syntax highlighting is not incremental, so it invokes Prism on each keystroke. This could be solved by using Lezer instead.

**Comment by marijnh** [comment]
Lezer isn't a complete highlighting system—a tree just gives you node names, and doesn't yet tell you which nodes should be styled how. As such, I think this is out of scope.
