### ISSUE TITLE
Resetting contexts on new parse

### ISSUE THREAD

**Issue by jun-sheaf** [lezer-parser/lezer#50]
I am building an `ExternalTokenizer` that requires a new context for every full parse, however it doesn't seem possible. Perhaps the most natural method would be to reset the context whenever the `@top` node is shifted, but a `@top` term is never called in the `ContextTracker`.

**Comment by marijnh** [comment]
Context should be restarted for every parse. (And shouldn't be mutated — maybe that's what's going wrong?)

**Comment by jun-sheaf** [comment]
I am a bit confused; so for a bit more context (pun intended), I gave the context tracker a start context, and during the parsing of the document, this context is updated (not mutated; simply a new updated context is provided) through the shift callback. After the parse has finished, there is no mechanism to reset the context back to a start state.
