### ISSUE TITLE
Enabling multiple dialects per token

### ISSUE THREAD

**Issue by jun-sheaf** [lezer-parser/lezer#51]
It seems Lezer does not natively support multiple dialects for tokens (using `,` or ` ` as the delimiters). Is it possible to include support for this? An abstract use case would be for any dialects that are the meet of two distinct others.

**Comment by marijnh** [comment]
This was considered during the design of dialects, and rejected as too much complexity (either at run-time, where a system that does more than just read a single boolean per token would be expensive, or at compile-time, if we were to use a system that precomputed the value of all boolean dialect expressions used in the grammar). You can use arbitrary expressions with dialects in custom tokenizers via [`dialectEnabled`](https://lezer.codemirror.net/docs/ref/#lezer.Stack.dialectEnabled), which can be a useful escape hatch here. Does that work for you?

**Comment by jun-sheaf** [comment]
The current work around we've been using is what you mentioned. In any case, you've looked into it; if you feel the ramifications are too great for implementation, then we concede. 😁
