### ISSUE TITLE
Could you add the [dist] directory?

### ISSUE THREAD

**Issue by liuwin7** [lezer-parser/lezer#52]
please include the **dist** directory to support the dynamic import? 
your package.json says
```
  "exports": {
    "import": "./dist/index.es.js",
    "require": "./dist/index.cjs"
  },
```

**Comment by liuwin7** [comment]
Sorry for the wondering description.
Here is the detail,
I use the [repo](https://github.com/GoogleChromeLabs/pwa-workshop-codelab) to learn the PWA.
There is an error when I start the project.
```
GET http://localhost:8080/@npm/lezer net::ERR_ABORTED 500 (Internal Server Error)
```
The project is based on the [WMR](https://github.com/preactjs/wmr), as it says `Safely import "packages" from npm without installation`. 

It can import other repos like **lezer-html**/**lezer-css** except the **lezer**. 

I don't know the WMR's import mechanism clearly. But I contrast the difference between the lezer and others finding that the lezer's directory structure is different from the others, missing the **dist** directory.

So, I make this issue above.

BTW, the origin [repo](https://github.com/GoogleChromeLabs/pwa-workshop-codelab) uses the [CodeMirror](https://codemirror.net/) to make an Editor. The CodeMirror depends on the **lezer**.

**Comment by marijnh** [comment]
`lezer` also comes with a `dist` directory (only when built, so it's not in git, but that's also the case with all the other packages).

**Comment by liuwin7** [comment]
Alright, maybe I should open an issue on GoogleChromeLabs.
Thanks a lot.
