### ISSUE TITLE
Ambiguity and recursion

### ISSUE THREAD

**Issue by edeboursetty** [lezer-parser/lezer#53]
Hi,

Let's say I have a grammar that's like:

```
Top => 
  TopAssignExpression |
  Expression

TopAssignExpression =>
  Variable = Expression

Expression =>
  Number |
  AssignExpression |
  ...

AssignExpression =>
  Variable = Expression
```

I have an ambiguity because `a = 2` could be potentially be parsed as a `TopAssignExpression`, or an `Expression` (as an `AssignExpression`. Now I want to always parse as a `TopAssignExpression` if it's possible.

In lezer, I am trying to do it that way:
```
@top Test {
  TopAssignExpression[@dynamicPrecedence=10] { VariableName "=" expression ~blah } |
  Expression[@dynamicPrecedence=-10] { expression }
}

expression {
  Number |
  AssignExpression { VariableName "=" expression } |
  PostFixExpr { expression ~blah "!" }
}

VariableName { identifier }
``` 

But lezer will parse `a = b =` as an `Expression` not a `TopAssignExpression`.

Can anyone help me? I am probably not doing this properly...

**Comment by marijnh** [comment]
You don't need dynamic precedence for this -- just a regular precedence (`@precedence { topAssign }`) and a marker after the `"="` in the `TopAssignExpression` rule (`!topAssign`) should do.

**Comment by edeboursetty** [comment]
Thank you so much for the quick answer (as always I guess).

I tried what you said, and that worked but I had to add the @cut modifier to the precedence. Reading the doc, I think that's exactly what I needed (at least it worked in my tests).

Thanks again
