### ISSUE TITLE
Support Typescript output

### ISSUE THREAD

**Issue by Timmmm** [lezer-parser/lezer#54]
`lezer-generator` should support generating Typescript output files. I think currently they would look the same as the Javascript ones but it would allow improved typing as described in #35.

At the very least it should let you specify `--output foo.ts` without writing to `foo.ts.js` (if I were you I would remove the automatic addition of `.js` altogether; that's just inconvenient magic).

**Comment by marijnh** [comment]
Attached patch makes the script less dumb about extensions. I'm not going to break existing behavior of adding an extension, and until the TS output would look any different from the non-TS output, it also doesn't seem necessary to add a switch for that.

**Comment by Timmmm** [comment]
The Typescript output *currently* looks the same but explicitly supporting Typescript allows outputting better Typescript code in future (for example the `["node", "names"] as const` array I discussed [here](https://github.com/lezer-parser/lezer/issues/35#issuecomment-889179503).

I can see you're not really interested in improved static typing though. :-/
