### ISSUE TITLE
Is there no way to identify which missing token(s) triggered an error node?

### ISSUE THREAD

**Issue by stuffaboutpete** [lezer-parser/lezer#56]
Love the project.

I think I know the answer to this but I have to ask... Is there no way for the parser to reveal more information about a zero-length error node? I think it's fair to say that a zero-length error node means no valid token could be found at that position. Can we not know which tokens would have been valid.

Beyond that, does anyone have an elegant solution for _working it out_? I can't imagine at the moment how to do this without writing code to re-describe the grammar and calculate it programatically. That seems like a big undertaking to me, to catch all the many ways a missing token could trigger an error node. But I have a vague feeling that there could be an elegant/simple way...

Any thoughts appreciated.

**Comment by marijnh** [comment]
Unfortunately, no. Lezer trees are very compact, minimal data structures, so that they can be cheaply created for large amounts of code. Putting any additional information, such as error context information, into them would be at odds with that design. As such, Lezer isn't much use as a linter.

**Comment by stuffaboutpete** [comment]
I understand and appreciate the answer, thank you.
