### ISSUE TITLE
Javascript keyword `eval` issue

### ISSUE THREAD

**Issue by drgrice1** [lezer-parser/lezer#57]
The keyword `eval` is missing from the `KEYWORDS` in the `generator/src/build.ts` file.  As a result if a language has that keyword it cause the compilation of the parser to fail.

**Comment by marijnh** [comment]
Can you show an example of a grammar that causes this problem? JavaScript's `eval` is not a keyword like, say, `function` is. It can be rebound like and locally shadowed like any regular identifier.

**Comment by drgrice1** [comment]
I have been working on writting a grammar for a language that has the token `eval` (it happens to be Perl).  If that shows up in the `parser.terms.js` file, the compilation of the parser fails with the warning `!] RollupError: src/parser.terms.js (94:4): 'eval' and 'arguments' cannot be used as a binding identifier in strict mode`.

Yes, technically `eval` is not a keyword for javascript in the same sense as the others in the list.

How do you rebound and locally shadow the identifier?

**Comment by marijnh** [comment]
Looks like it's a non-strict-only thing (you can simply do `let eval = 2` etc). But yeah, this should work in strict mode, so I'll add those to the list of keywords.
