### ISSUE TITLE
Introduce `@unexpected` and `@missing` Node Types for Error Handling

### ISSUE THREAD

**Issue by binhtddev** [lezer-parser/lezer#59]
Treesitter supports the generation of `Unexpected` and `Missing` nodes during tree parsing. However, Lezer currently uses a generic `⚠` token, making it difficult for users to write test cases. To enhance usability, I propose introducing `@unexpected` and `@missing` as built-in node types. The `@missing` node should include information about the missing token to facilitate specific test case scenarios.

**Comment by marijnh** [comment]
Could you say a bit more about how these would work?

**Comment by binhtddev** [comment]
> Could you say a bit more about how these would work?

Currently developing an LSP implementation using Lezer, I'm encountering challenges with the generic `⚠` token used to represent unexpected and missing tokens. While I can detect unexpected tokens by checking their length, the `⚠` token lacks sufficient information to generate meaningful hints for missing tokens. To address this, I propose splitting the `⚠` token into more specific `@unexpected` and `@missing` node types.

**Comment by marijnh** [comment]
The @ notation suggests they would be part of the grammar syntax, but I guess that's not what you mean? These would be standard node types present in every set, like the error type currently is, and the LR parser would assign different error situation different node types?

There's more than just two types of errors (early node cut off, reached end of grammar, invalid token, etc), though. And unfortunately, it'd be very hard to introduce new 'hard coded' node types in the set of node IDs in a backwards-compatible way.

**Comment by binhtddev** [comment]
> And unfortunately, it'd be very hard to introduce new 'hard coded' node types in the set of node IDs in a backwards-compatible way.

Thank you for your response.

I propose an alternative approach: providing functions to retrieve all missing nodes within a given node or its children. This would offer more flexibility than relying solely on the `@missing` node, especially when determining which specific tokens are absent.

If accurately identifying missing tokens proves challenging, this method would still provide valuable information for error handling and recovery.

**Comment by marijnh** [comment]
Where would this information come from though?

**Comment by binhtddev** [comment]
> Where would this information come from though?

Apologies for the interruption. Initially, I believed retrieving missing nodes directly would be simpler. However, upon further consideration, the complexities involved in implementation are unclear. Therefore, I'll close this issue for now. Thank you for your time and consideration.
