### ISSUE TITLE
TreeCursor.iterate continues iterating over sibling nodes

### ISSUE THREAD

**Issue by peaffenzeller** [lezer-parser/lezer#60]
The docs for [`TreeCursor.iterate`](https://lezer.codemirror.net/docs/ref/#common.TreeCursor.iterate) say

> Iterate over the current node and all its descendants, [...]

That would suggest, that siblings of a node are not included when iterating, only its children. But when I create a new cursor for a given node and call `iterate` on it, it continues iterating also over sibling nodes, [see this example](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge2phdmFzY3JpcHR9IGZyb20gIkBjb2RlbWlycm9yL2xhbmctamF2YXNjcmlwdCIKaW1wb3J0IHsgc3ludGF4VHJlZSB9IGZyb20gJ0Bjb2RlbWlycm9yL2xhbmd1YWdlJzsKCmNvbnN0IHZpZXcgPSBuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAiY29uc3QgYSA9IDE7XG5jb25zdCBiID0gMjsiLAogIGV4dGVuc2lvbnM6IFtiYXNpY1NldHVwLCBqYXZhc2NyaXB0KCldLAogIHBhcmVudDogZG9jdW1lbnQuYm9keQp9KTsKCmNvbnN0IHRyZWUgPSBzeW50YXhUcmVlKHZpZXcuc3RhdGUpOwpjb25zdCBjdXJzb3IgPSB0cmVlLmN1cnNvckF0KDApOwoKY3Vyc29yLml0ZXJhdGUoKG5vZGUpID0+IHsKICAKICBpZiAobm9kZS5uYW1lID09PSAnVmFyaWFibGVEZWNsYXJhdGlvbicpIHsKICAgIGNvbnNvbGUubG9nKCdlbnRlcmluZyBWYXJpYWJsZURlY2xhcmF0aW9uJykKICAgIGNvbnN0IGxvY2FsQ3Vyc29yID0gbm9kZS5ub2RlLmN1cnNvcigpOwoKICAgIGNvbnNvbGUubG9nKCctLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0nKQogICAgbG9jYWxDdXJzb3IuaXRlcmF0ZSgobG9jYWxOb2RlKSA9PiB7CiAgICAgIGNvbnNvbGUubG9nKGxvY2FsTm9kZS5uYW1lLCAnOyBub2RlIHRleHQ6ICcsIHZpZXcuc3RhdGUuZG9jLnNsaWNlKGxvY2FsTm9kZS5mcm9tLCBsb2NhbE5vZGUudG8pLnRvU3RyaW5nKCkpOwogICAgfSkKICAgIGNvbnNvbGUubG9nKCctLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0nKQogIH0KfSwgKG5vZGUpID0+IHsKICBpZiAobm9kZS5uYW1lID09PSAnVmFyaWFibGVEZWNsYXJhdGlvbicpIHsKICAgIGNvbnNvbGUubG9nKCdsZWF2aW5nJykKICB9Cn0pOw==).

the new cursor used to iterate over the `VariableDeclaration` logs both `const a = 1` and `const b = 2`, even though - according to the docs - it should stop after its last child.

**Comment by marijnh** [comment]
That was indeed a bug. Attached patch should fix it.

**Comment by JClackett** [comment]
Think this has caused a regression, getting: TypeError: undefined is not an object (evaluating 'children.length') now

**Comment by marijnh** [comment]
I suspect you upgraded incorrectly, and have duplicated @lezer packages in your node_modules.

**Comment by JClackett** [comment]
im using codemirror which depends on lezer apparantly, so dont have lezer in my package json. Reverting to 1.2.2 has solved for now :)

**Comment by marijnh** [comment]
`yarn upgrade` (or `npm upgrade` in old npm versions) will duplicate some dependencies that are depended on in multiple ways, leading to, for example, `instanceof` becoming unreliable because classes are loaded multiple times.

**Comment by JClackett** [comment]
Sorry im not really sure what you mean, if I look in my lock file after my app started crashing, I see that this package was updated to 1.2.3, so if I set the resolutions property to keep lezer at 1.2.2 it fixes my issues. The stack trace of the error leads back to this package causing the error. Is that not an issue with this package then?

**Comment by marijnh** [comment]
In the broken state, what does `npm ls -a | grep @lezer` give?

**Comment by JClackett** [comment]
hmm yeah, actually, if I set the resolutions to 1.2.3 it works as well, so for some reason my lock file changed and there was a broken version or something weird happening?
