### ISSUE TITLE
Is there a way to tell the parser not to attempt a certain recovery path?

### ISSUE THREAD

**Issue by stuffaboutpete** [lezer-parser/lezer#61]
The following is valid syntax in my example language (a simplified version of a real project):

```
Resource ExampleOne {
  Key {
    Key 123
  }
}

Type ExampleTwo {
  Key Value
}
```

I have `Resource`s and I have `Type`s. The two are quite similar but not the same. I want all declarations at the top level of the document to start with either the keyword `Resource` or the keyword `Type`. If the parser does not find one of these two keywords, I don't want it to attempt a recovery, I want it to move onto the next token and start looking for a resource or type keyword again.

Is this possible? I thought the answer might lie in a `@cut` precedence but I can't quite get my head around whether that is right? All of my experiments around that yielded no progress.

My grammar:

```
@top Document { entity* }

@skip { space }

@tokens {
    space { @whitespace+ }
    BooleanLiteral { "true" | "false" }
    NumberLiteral { "-"? $[0-9]+ ("." $[0-9]+)? }
    Identifier { $[A-Za-z0-9_]+ }
    Key { $[A-Z] $[A-Za-z]* }
}

ResourceBlock { "{" ResourceKeyValue* "}" }
ResourceKeyValue { Key value }
value { BooleanLiteral | NumberLiteral | ResourceBlock }

TypeParameters { "<" Identifier+ ">" }
TypeBlock { "{" TypeKeyValue* "}" }
TypeKeyValue { Key Identifier }

Resource { "Resource" Identifier ~identifier ResourceBlock }
Type { "Type" Identifier ~identifier TypeParameters? TypeBlock }
entity { Resource | Type }

```

Many thanks.

**Comment by marijnh** [comment]
No, the tool currently doesn't really provide any control over error-recovery. You can sometimes create rules that represent common invalid constructs, and parse those instead of letting the recovery handle them, but that's the only real option you have for this.
