### ISSUE TITLE
Does Lezer support (or plan to support) local variables?

### ISSUE THREAD

**Issue by jason5122** [lezer-parser/lezer#7]
Hi, does Lezer support local variables like [tree-sitter does](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables)? In tree-sitter, I can declare local scopes and have one variable appear with a consistent style across the scope. Here is an example below. Note that the underlined variables appear in either a method argument/for loop declaration and remain underlined throughout the scope.

<img width="412" alt="Screen Shot 2020-12-09 at 6 14 19 PM" src="https://user-images.githubusercontent.com/34594853/101700237-b5fa4200-3a4a-11eb-8dc5-92ed3876dd39.png">

Thanks! I stumbled on your write-up on Lezer and since I already really love tree-sitter (moved to that recently; been stuck with tmLanguage/sublime-syntax for far too long), I really hope this project takes off :)

**Comment by marijnh** [comment]
I looked into this and set up a working prototype, but decided that the performance impact was bigger than what I'm comfortable paying for the more detailed highlighting.

**Comment by jason5122** [comment]
That's unfortunate, but it makes sense. Thanks for testing it out!
