### ISSUE TITLE
lezer-generator message: Node has properties but no name

### ISSUE THREAD

**Issue by dxparker** [lezer-parser/lezer#8]
Running lezer-generator against the grammar below, taken from the Writing a Grammar section of the lezer documentation, exits with message: `Node has properties but no name`. I get the same results using a local build or using npx to run the lezer-generator on npm (v0.5.1)

```
bin/lezer-generator simple.grammar -o simple.js
```

Contents of `simple.grammar`:
```
@top { expression }

expression { Name | Number | BinaryExpression }

BinaryExpression { "(" expression ("+" | "-") expression ")" }

@tokens {
  Name { std.asciiLetter+ }
  Number { std.digit+ }
}
```

**Comment by marijnh** [comment]
Ugh, I made a small change without thinking about it very much and of course it broke everything. Attached patch should help.

**Comment by marijnh** [comment]
Where "attached patch" is https://github.com/lezer-parser/lezer-generator/commit/8a9aae09fa3376b5325a9be72222be1af1e9c744
